# Generated by Django 2.0.4 on 2018-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='events',
            field=models.ManyToManyField(blank=True, to='map.Event'),
        ),
        migrations.AddField(
            model_name='location',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='map.Rating'),
        ),
    ]
