# Generated by Django 2.0.4 on 2018-04-20 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 20, 20, 35, 32, 457898)),
        ),
    ]
