# Generated by Django 2.0.4 on 2018-04-20 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20180420_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 20, 20, 56, 33, 507227)),
        ),
    ]
