# Generated by Django 2.0.4 on 2018-05-04 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20180420_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='events',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 4, 14, 18, 46, 762062)),
        ),
    ]
